version: '3.4'

networks:
  assignment-network:
    driver: bridge

services:
  assignment.api:
    container_name: assignment-api
    image: ${DOCKER_REGISTRY-}assignmentapi
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: Assignment.Api/Dockerfile
    depends_on:
      - assignment-db
    networks:
      - assignment-network
  
  assignment-db:
    container_name: assignment-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - assignment-network

volumes:
  postgres-data: